// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: drink.sql

package db

import (
	"context"
)

const getDrinks = `-- name: GetDrinks :many
SELECT id, name, img, description, price FROM "drink"
`

func (q *Queries) GetDrinks(ctx context.Context) ([]Drink, error) {
	rows, err := q.db.QueryContext(ctx, getDrinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Drink
	for rows.Next() {
		var i Drink
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Img,
			&i.Description,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
