// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: food.sql

package db

import (
	"context"
)

const getFoods = `-- name: GetFoods :many
SELECT id, name, img, description, price FROM "food"
`

func (q *Queries) GetFoods(ctx context.Context) ([]Food, error) {
	rows, err := q.db.QueryContext(ctx, getFoods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Food
	for rows.Next() {
		var i Food
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Img,
			&i.Description,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
