// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Drink struct {
	ID          int64
	Name        string
	Img         string
	Description string
	Price       int64
}

type Food struct {
	ID          int64
	Name        string
	Img         string
	Description string
	Price       int64
}

type Meal struct {
	ID          int64
	Name        string
	Img         string
	Description string
	Price       int64
}

type User struct {
	ID       int64
	Name     string
	Email    string
	Password string
}
